version: "3.8"

services:
  db:
    image: postgres:15
    container_name: notes_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: first123
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # For healthy check:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: notes_app
    ports:
      - "8000:8000"
    # Condition based:
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:first123@db:5432/notes_db
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_SECRET: ${ADMIN_SECRET}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

volumes:
  postgres_data: